services:
  mongodb:
    image: mongo:8.2.7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --eval \"quit(db.adminCommand({ ping: 1 }).ok ? 0 : 1)\"",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis:
    image: redis:8.0.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongodb_data:
  redis_data:
